#    _       _      _ _
#   (_)_   _(_) ___(_) |_ _   _
#   | | | | | |/ __| | __| | | |
#   | | |_| | | (__| | |_| |_| |
#  _/ |\__,_|_|\___|_|\__|\__, |
# |__/                    |___/
#
# Copyright (C) 2023 @juicity <https://github.com/juicity>
#
# This is a open-source software, liscensed under the AGPL-3.0 License.
# See /License for more information.

name: Daily Build (Main)

on:
  schedule:
    # At (UTC+8 0:00 | UTC+0 16:00) every day
    - cron: "0 16 * * *"

jobs:
  pre-actions:
    uses: daeuniverse/ci-seed-jobs/.github/workflows/pre-actions.yml@master
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.sha }}
      fetch-depth: 0
      check-runs: '["build", "daily-build-passed"]'
    secrets: inherit

  build:
    uses: juicity/juicity/.github/workflows/seed-build.yml@main
    with:
      ref: ${{ github.sha }}
      build-type: daily-build

  post-actions:
    if: always()
    needs: [build]
    uses: daeuniverse/ci-seed-jobs/.github/workflows/juicity-post-actions.yml@master
    with:
      check-run-id: "juicity-bot[bot]/daily-build-passed"
      check-run-conclusion: ${{ needs.build.result }}
    secrets: inherit
