#    _       _      _ _
#   (_)_   _(_) ___(_) |_ _   _
#   | | | | | |/ __| | __| | | |
#   | | |_| | | (__| | |_| |_| |
#  _/ |\__,_|_|\___|_|\__|\__, |
# |__/                    |___/
#
# Copyright (C) 2023 @juicity <https://github.com/juicity>
#
# This is a open-source software, liscensed under the AGPL-3.0 License.
# See /License for more information.

name: Seed Release Build

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
        default: ${{ github.ref }}

jobs:
  build:
    strategy:
      matrix:
        goos: [ linux ]
        goarch: [ arm64, 386, riscv64, mips64, mips64le, mipsle, mips ]
        include:
          # BEGIN Linux ARM 5 6 7
          - goos: linux
            goarch: arm
            goarm: 7
          - goos: linux
            goarch: arm
            goarm: 6
          - goos: linux
            goarch: arm
            goarm: 5
          # END Linux ARM 5 6 7
          # BEGIN Linux AMD64 v1 v2 v3
          - goos: linux
            goarch: amd64
            goamd64: v1
          - goos: linux
            goarch: amd64
            goamd64: v2
          - goos: linux
            goarch: amd64
            goamd64: v3
          # END Linux AMD64 v1 v2 v3
          # BEGIN Darwin ARM64 AMD64
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
          # END Darwin ARM64 AMD64
          # BEGIN Windows ARM64 AMD64
          - goos: windows
            goarch: amd64
          - goos: windows
            goarch: arm64
          # END Windows ARM64 AMD64
          # BEGIN Android ARM64
          - goos: android
            goarch: arm64
          # END Android ARM64
      fail-fast: false

    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOARM: ${{ matrix.goarm }}
      GOAMD64: ${{ matrix.goamd64 }}
      CGO_ENABLED: 0

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0

      - name: Get the version
        id: get_version
        env:
          REF: ${{ inputs.tag }}
        run: |
          version=${REF}
          echo "VERSION=$version" >> $GITHUB_OUTPUT
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Show workflow information
        id: get_filename
        run: |
          export _NAME=$(jq ".[\"$GOOS-$GOARCH$GOARM$GOAMD64\"].friendlyName" -r < install/friendly-filenames.json)
          echo "GOOS: $GOOS, GOARCH: $GOARCH, RELEASE_NAME: $_NAME"
          echo "ASSET_NAME=$_NAME" >> $GITHUB_OUTPUT
          echo "ASSET_NAME=$_NAME" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.21'

      - name: Get project dependencies
        run: |
          git submodule update --init --recursive
          GOMODCACHE="${PWD}"/go-mod go mod download -modcacherw
          find ./go-mod/ -maxdepth 1 ! -name "cache" ! -name "go-mod" -exec rm -rf {} \;
          sed -i 's/#export GOMODCACHE=$(PWD)\/go-mod/export GOMODCACHE=$(PWD)\/go-mod/' Makefile

      - name: Create full source ZIP archive and Signature
        if: matrix.goarch == 'amd64' && matrix.goamd64 == 'v1'
        run: |
          zip -9vr juicity-full-src.zip . -x .git/\*
          FILE=./juicity-full-src.zip
          echo "$(md5sum $FILE)""  md5" >> $FILE.dgst
          echo "$(shasum -a 1 $FILE)""  sha1" >> $FILE.dgst
          echo "$(shasum -a 256 $FILE)""  sha256" >> $FILE.dgst
          echo "$(shasum -a 512 $FILE)""  sha512" >> $FILE.dgst

      - name: Build juicity
        run: |
          mkdir -p ./build/
          export CGO_ENABLED=0
          export GOFLAGS="-trimpath -modcacherw"
          export VERSION=${{ steps.get_version.outputs.VERSION }}
          make
          cp ./juicity-server ./build/
          cp ./juicity-client ./build/

      - name: Rename windows name
        if: matrix.goos == 'windows'
        run: |
          mv ./build/juicity-server ./build/juicity-server.exe
          mv ./build/juicity-client ./build/juicity-client.exe

      - name: Copy systemd service
        if: matrix.goos == 'linux'
        run: |
          cp ./install/example-{client,server}.json ./build/
          cp ./install/juicity-{client,server}.service ./build/

      - name: Smoke test
        if: matrix.goarch == 'amd64' && matrix.goamd64 == 'v1'
        run: |
          ./build/juicity-server -v
          ./build/juicity-client -v

      - name: Create binary ZIP archive and Signature
        run: |
          pushd build || exit 1
          zip -9vr ../juicity-$ASSET_NAME.zip .
          popd || exit 1
          FILE=./juicity-$ASSET_NAME.zip
          echo "$(md5sum $FILE)""  md5" >> $FILE.dgst
          echo "$(shasum -a 1 $FILE)""  sha1" >> $FILE.dgst
          echo "$(shasum -a 256 $FILE)""  sha256" >> $FILE.dgst
          echo "$(shasum -a 512 $FILE)""  sha512" >> $FILE.dgst

      - name: Upload files to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: juicity-${{ steps.get_filename.outputs.ASSET_NAME }}.zip
          path: ./*.zip*

      # - name: Report result
      #   uses: daeuniverse/ci-seed-jobs/common/report-check-run@master
      #   if: always()
      #   with:
      #     app_id: ${{ secrets.GH_APP_ID }}
      #     private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      #     id: "juicity-bot[bot]/build"
